### PR TITLE
Enable compatibility with libconfig older than v1.5

### PR DESCRIPTION
**Pull request by abraha2d**
libconfig v1.4.9 is the latest version available in the RHEL / CentOS 7 repos, but `Setting.lookup()` was only added in v1.5.
This PR allows logiops to be compiled on these operating systems.

### CODE REVIEW

**Comment by PixlOne** [comment]
Thanks, I didn't know this was incompatible with older versions.

**Comment by JMoerman** [comment]
This PR broke compatibility with Ubuntu 18.04:
```
build_dir/src/logid/features/ThumbWheel.cpp: In static member function ‘static std::shared_ptr<logid::actions::Action> logid::features::ThumbWheel::Config::_genAction(logid::Device*, libconfig::Setting&, const string&)’:
build_dir/src/logid/features/ThumbWheel.cpp:230:36: error: no match for ‘operator[]’ (operand types are ‘libconfig::Setting’ and ‘const string {aka const std::__cxx11::basic_string<char>}’)
         auto& a_group = config_root[name];
                                    ^
In file included from build_dir/src/logid/features/../actions/gesture/../Action.h:22:0,
                 from build_dir/src/logid/features/../actions/gesture/Gesture.h:21,
                 from build_dir/src/logid/features/ThumbWheel.h:23,
                 from build_dir/src/logid/features/ThumbWheel.cpp:19:
/usr/include/libconfig.h++:223:13: note: candidate: libconfig::Setting& libconfig::Setting::operator[](const char*) const
   Setting & operator[](const char *name) const;
             ^~~~~~~~
/usr/include/libconfig.h++:223:13: note:   no known conversion for argument 1 from ‘const string {aka const std::__cxx11::basic_string<char>}’ to ‘const char*’
/usr/include/libconfig.h++:224:13: note: candidate: libconfig::Setting& libconfig::Setting::operator[](int) const
   Setting & operator[](int index) const;
             ^~~~~~~~
/usr/include/libconfig.h++:224:13: note:   no known conversion for argument 1 from ‘const string {aka const std::__cxx11::basic_string<char>}’ to ‘int’
build_dir/src/logid/features/ThumbWheel.cpp: In static member function ‘static std::shared_ptr<logid::actions::Gesture> logid::features::ThumbWheel::Config::_genGesture(logid::Device*, libconfig::Setting&, const string&)’:
build_dir/src/logid/features/ThumbWheel.cpp:247:36: error: no match for ‘operator[]’ (operand types are ‘libconfig::Setting’ and ‘const string {aka const std::__cxx11::basic_string<char>}’)
         auto& g_group = config_root[name];
                                    ^
In file included from build_dir/src/logid/features/../actions/gesture/../Action.h:22:0,
                 from build_dir/src/logid/features/../actions/gesture/Gesture.h:21,
                 from build_dir/src/logid/features/ThumbWheel.h:23,
                 from build_dir/src/logid/features/ThumbWheel.cpp:19:
/usr/include/libconfig.h++:223:13: note: candidate: libconfig::Setting& libconfig::Setting::operator[](const char*) const
   Setting & operator[](const char *name) const;
             ^~~~~~~~
/usr/include/libconfig.h++:223:13: note:   no known conversion for argument 1 from ‘const string {aka const std::__cxx11::basic_string<char>}’ to ‘const char*’
/usr/include/libconfig.h++:224:13: note: candidate: libconfig::Setting& libconfig::Setting::operator[](int) const
   Setting & operator[](int index) const;
             ^~~~~~~~
```

**Comment by PixlOne** [comment]
@abraha2d I'm looking at [libconfig 1.4.9 on the CentOS repos](https://centos.pkgs.org/7/centos-x86_64/libconfig-1.4.9-5.el7.x86_64.rpm.html) and it appears that it does have support for .lookup(). Can you post the errors you were getting when compiling before this PR?

Also, because of bug #158, I'm going to have to revert this change.

**Comment by abraha2d** [comment]
This is the error I was encountering:
```
logiops/src/logid/Configuration.cpp: In constructor ‘logid::Configuration::Configuration(const string&)’:
logiops/src/logid/Configuration.cpp:101:29: error: ‘const class libconfig::Setting’ has no member named ‘lookup’
  101 |         auto& ignore = root.lookup("ignore");
      |                             ^~~~~~
logiops/src/logid/Configuration.cpp:119:33: error: ‘const class libconfig::Setting’ has no member named ‘lookup’
  119 |             auto& ignore = root.lookup("blacklist");
      |                                 ^~~~~~
make[2]: *** [src/logid/CMakeFiles/logid.dir/build.make:161: src/logid/CMakeFiles/logid.dir/Configuration.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:114: src/logid/CMakeFiles/logid.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

**Comment by abraha2d** [comment]
libconfig v1.4.9 has Config.lookup(), but it does not have Setting.lookup(). Setting.lookup() was added in v1.5 to unify the API between Config and Setting: https://github.com/hyperrealm/libconfig/commit/1ff9b7f9a2df1abbb5781b78d4065fa22bc5fad6.

The issue that's occurring with my PR is a mismatch between `const char*` and `const string` when trying to find the [] operator (which for some reason my compiler isn't complaining about). I'll see if I can fix and update the PR.

**Comment by PixlOne** [comment]
Alright, thanks.

**Comment by abraha2d** [comment]
I committed a fix over on abraha2d/logiops, but I don't currently have access to an Ubuntu system to verify that it fixes the issue...

**Comment by PixlOne** [comment]
@ightnapovial Could you test out the fix on https://github.com/abraha2d/logiops?

**Comment by abraha2d** [comment]
fwiw I was able to test that it compiles successfully on KDE neon 5.19 (based on Ubuntu 18.04) with GCC 10.1.0.

**Comment by abraha2d** [comment]
@PixlOne Any updates on this? I've got some more PRs that are in draft (#160 and #161) pending resolution of this.

**Pull request merged**
