### PR TITLE
Fix ThumbWheel feature direction bug

### LINKED ISSUE #145: Thumbwheel / Horizontal wheel on MX Master
For more than 30 minutes I've been trying to get the thumbwheel working on my MX Master...  
I've looked at #106, but that seems to be related only to the MX Master 3  
  
My goal is to have my thumbwheel influence my volume levels.  

Right now this is my thumbwheel **config**, taken from #106 :
```
thumbwheel:
{
	divert: true
	invert: false
	left: {	
		mode: "OnInterval"
		pixels: 1
		action: { 
			type: "Keypress"
			keys: ["KEY_VOLUMEUP"]
		}
	}
	right: {
		mode: "OnInterval"
		pixels: 1
		action: { 
			type: "Keypress"
			keys: ["KEY_VOLUMEDOWN"] 
		}
	}
};
```  

**evtest** on my thumbwheel value -1 is moving it up (right, if using horizontal scroll), and 1 being down (left):
```
Event: time 1603757361.144572, type 2 (EV_REL), code 6 (REL_HWHEEL), value -1
Event: time 1603757361.144572, type 2 (EV_REL), code 12 (REL_HWHEEL_HI_RES), value -120
Event: time 1603757361.144572, -------------- SYN_REPORT ------------
Event: time 1603757362.376575, type 2 (EV_REL), code 6 (REL_HWHEEL), value 1
Event: time 1603757362.376575, type 2 (EV_REL), code 12 (REL_HWHEEL_HI_RES), value 120
Event: time 1603757362.376575, -------------- SYN_REPORT ------------
```

**logid -v DEBUG**
```
[INFO] Device found: Wireless Mouse MX Master on /dev/hidraw6:1
[DEBUG] /dev/hidraw6:1 remappable buttons:
[DEBUG] CID  | reprog? | fn key? | mouse key? | gesture support?
[DEBUG] 0x50 |         |         | YES        | 
[DEBUG] 0x51 |         |         | YES        | 
[DEBUG] 0x52 | YES     |         | YES        | YES
[DEBUG] 0x53 | YES     |         | YES        | YES
[DEBUG] 0x56 | YES     |         | YES        | YES
[DEBUG] 0xc3 | YES     |         | YES        | YES
[DEBUG] 0xc4 | YES     |         | YES        | YES
[DEBUG] 0xd7 | YES     |         |            | YES
```

**hidpp-list-devices**
```
/dev/hidraw6: Logitech USB Receiver (046d:c52b) HID++ 1.0
/dev/hidraw6 (device 1): MX Master (046d:4069) HID++ 4.5
```  

**hidpp-list-features /dev/hidraw6 -d 1**
```
MX Master (046d:4069) is a HID++ 4.5 device
Feature 0x01: [0x0001] Feature set
Feature 0x02: [0x0003] Device FW version
Feature 0x03: [0x0005] Device name
Feature 0x04: [0x1d4b] Wireless device status
Feature 0x05: [0x0020] Reset
Feature 0x06: [0x0021] Crypto Identifier
Feature 0x07: [0x1000] Battery status
Feature 0x08: [0x1806] Configurable device properties (hidden, internal)
Feature 0x09: [0x1814] Change host
Feature 0x0a: [0x1b04] Reprog controls v4
Feature 0x0b: [0x2201] Adjustable dpi
Feature 0x0c: [0x2100] Vertical scrolling
Feature 0x0d: [0x2110] Smart shift
Feature 0x0e: [0x2121] Hi-res wheel
Feature 0x0f: [0x6501] Gesture 2
Feature 0x10: [0x00c2] DFUcontrol 3
Feature 0x11: [0x1813] ? (hidden, internal)
Feature 0x12: [0x1830] ? (hidden, internal)
Feature 0x13: [0x1890] ? (hidden, internal)
Feature 0x14: [0x1891] ? (hidden, internal)
Feature 0x15: [0x18a1] ? (hidden, internal)
Feature 0x16: [0x18c0] ? (hidden, internal)
Feature 0x17: [0x1df3] ? (hidden, internal)
Feature 0x18: [0x1e00] Enable hidden features (hidden)
Feature 0x19: [0x1eb0] ? (hidden, internal)
Feature 0x1a: [0x1803] ? (hidden, internal)
Feature 0x1b: [0x1861] ? (hidden, internal)
Feature 0x1c: [0x9001] ? (hidden, internal)
Feature 0x1d: [0x9200] ? (hidden, internal)
Feature 0x1e: [0x9202] ? (hidden, internal)
Feature 0x1f: [0x1805] OOBState (hidden, internal)
```
  
Maybe I am just retarded, but I am quite new to all of this :)

### PR DESCRIPTION
**Pull request by PixlOne**
Should fix #145 for the MX Master 3

Thank you @Gorzen for this change, this is basically your change just cleaned up a bit.

### CODE REVIEW

**Comment by PixlOne** [comment]
@Starvexx @marxlaml Can you test this to make sure it works?

**Comment by marxlaml** [comment]
Works very well for me, way smoother than the 'workaround' too.

This is the config section I used to test:
```
thumbwheel: {
    divert: true;
    invert: false;
    left: {
        threshhold: 1;
        interval: 2;
        direction: "Left";
        mode: "OnInterval";
        action = { type: "Keypress"; keys: ["KEY_VOLUMEDOWN"] };
    };
    right: {
        threshhold: 1;
        interval: 2;
        direction: "Right";
        mode: "OnInterval";
        action = { type: "Keypress"; keys: ["KEY_VOLUMEUP"] };
    };
};
```

**Comment by Starvexx** [comment]
Works great for me as well and as @marxlaml already mentioned, it feels smoother than the workaround.

Heres my config file.

    thumbwheel:
    {
    	divert: true;
    	invert: false;
    	left:
        {
            threshold: 1;
            interval: 1;
            direction: "Left";
            mode: "OnInterval";
            action =
            {
            	type: "Keypress";
            	keys: ["KEY_VOLUMEDOWN"];
            };
        };
    	right:
    	{
            threshold: 1;
            interval: 1;
            direction: "Right";
            mode: "OnInterval";
            action =
            {
            	type: "Keypress";
            	keys: ["KEY_VOLUMEUP"];
            };
        };
	tap:
	{
	    type: "Keypress";
	    keys: ["KEY_MUTE"]
	};
    };

**Comment by outshrill** [comment]
Hi, I have added this to my confg file but doesnt work, it just do nothing

**Comment by outshrill** [comment]
It will be nice if we can add shift key pressed to add smoothness to the up down movement. I don't know how to add it because it has to be pressed all the time while thumbing the wheel.

**Comment by outshrill** [comment]
Finally I did it adding the touch option, this way the volume changing is smoother:

thumbwheel:
	   {
		divert: true;
		invert: false;
		
		left:{
		threshold: 1;
		interval: 1;
		direction: "Left";
		mode: "OnInterval";
		action = {type: "Keypress"; keys: ["KEY_VOLUMEDOWN"];};
		     };
		
		right:{
		threshold: 1;
		interval: 1;
		direction: "Right";
		mode: "OnInterval";
		action = {type: "Keypress"; keys: ["KEY_VOLUMEUP"];};
	              };
	              
	        tap:{
    		type: "Keypress";
    		keys: ["KEY_MUTE"]
		    };
		    
		touch:{
    		type: "Keypress";
    		keys: ["KEY_LEFTSHIFT"]
		    };
	    };

**Pull request merged**
