### PR TITLE
Resolve majority of clang+libstdc++ warnings

### PR DESCRIPTION
**Pull request by damageboy**

### CODE REVIEW

**Comment by PixlOne** [comment]
Thanks, this is a bit of a nitpick, but could you use spaces and make sure the changes are properly indented?

I'll approve this once this is done.

**Comment by damageboy** [comment]
Sure thing. will ping when done.

**Comment by damageboy** [comment]
Should be OK whitespace wise, I've added an extra commit to add an `.editorconfig` file to cement the whitespace policy of this project..

**Comment by damageboy** [comment]
pinging @PixlOne :)

**Pull request merged**
