### PR TITLE
Drop libhidpp and refactor code

### LINKED ISSUE #70: Use more modern C++ practices
In particular, the `new` keyword everywhere is somewhat worrying, even though this is just running in userspace. Perhaps an enhancement could be to use `std::unique_ptr` and `std::shared_ptr` where applicable?

### PR DESCRIPTION
**Pull request by PixlOne**
This project started as a way to move away from libhidpp and reduce issues with submodules and additional dependencies. I was planning to refactor the code in a separate branch, but I kind of got carried away and started working on the refactor during the development of the new backend.

These changes will:
- Reduce dependencies
- Improve code readability
- Reduce bugs by handling errors better
- Use more modern C++ practices (will fix #70 after applying to the master branch)

~~This pull request is currently targeting the feature/logictl branch since it was based on it but these changes will eventually be carried over to the master branch.~~

EDIT: This pull request is now targeting master, feature/logictl will be rebased on this and this branch will be rebased on master.

### CODE REVIEW

**Comment by PixlOne** [comment]
Status update: This branch is almost complete.

What's left:
- Gesture support
- CycleDPI/ChangeDPI action support
- NoAction support
- Final code review & cleaning
- Backporting to master branch (maybe, post-merge)

**Comment by rockerbacon** [comment]
I see that you are constantly creating new threads. That's generally not a good idea:
- Thread creation is expensive compared to creating one thread and reusing it
- This approach is prone to leaks. An accidental infinite loop where there shouldn't be one can lead to large amounts of threads being created and none being terminated, for example.

For what is being done here I believe using `std::async` with `std::launch::async` might be the cleaner approach:
- Doesn't require an extra thread util
- Is immediately familiar to C++ devs
- Delegates thread management to the compiler

When using `std::async`, remember that destruction of the returned `std::future` object will force the main thread to wait.

**Comment by PixlOne** [comment]
I'm actually working on a workqueue system right now. I noticed that I was spawning threads quite frequently and decided it would be better to have a few worker threads that I just dispatch tasks to.

I still plan to keep the listeners on separate threads though. @rockerbacon Should I make these listeners run on their own std::thread (via the logid::thread wrapper) or should I launch them with async functions.

**Comment by PixlOne** [comment]
Status update: All that's left at this point is some final bugfixes and code cleanup. 

Since this branch is much more stable and modern than the master branch, and I don't want to wait until the IPC feature is complete to deploy this, I'll rebase this on master and apply it to there.

If anyone is available to test this branch, please do and report on your findings. Also, go through any bug reports that have been filed and tell me if they have been fixed.

**Comment by PixlOne** [comment]
I've reworked the commit history of this branch on the refactor branch and I need to open a new PR to merge it.

See #99

**Pull request closed without merging**
