### PR TITLE
add M590 to list of tested devices

### PR DESCRIPTION
**Pull request by rumesh986**
Tested M590 on Arch linux as well Ubuntu 20.04. Everything in my tests worked.

Also noticed that libudev is not a valid package in arch linux. I am not sure what the actual package is but it seems I already had the required so file on my system. I also had to install pkgconf for cmake to work

### CODE REVIEW

**Comment by PixlOne** [comment]
What's with the change in the README.md?

I got those dependencies from the [logiops-git](https://aur.archlinux.org/packages/logiops-git/) package in the AUR. Also, if we do need to make changes to the dependencies list, it should be done in a different commit.

**Comment by rumesh986** [comment]
Split the commits.
Just wanted to update the installation instructions as it was missing the pkgconf packages

**Comment by PixlOne** [comment]
Can you clean up your branch so that it's only the two commits (`add M590 to list of tested devices` (a810a29) and `edit installation instructions for arch linux` (7e29a41))?

**Comment by rumesh986** [comment]
Ok, I changed it to only be two commits

**Comment by PixlOne** [comment]
Alright, thanks.

**Pull request merged**
