### PR TITLE
support smartshift(0x2111) on mx anywhere3

### PR DESCRIPTION
**Pull request by leios76**

### CODE REVIEW

**Comment by leios76** [comment]
reference: https://drive.google.com/file/d/1HT-ih4Zjb5yRx1ilyYsphYeXW_MTJ_X_/view?usp=sharing

**Comment by thhart** [comment]
Tested your patch, working well, nice work.

**Comment by leios76** [comment]
new configure keyword for smartshift v2(0x2111): torque (the current tunable torque in % of the maxForce)
```
    smartshift:
    {
        on: true;
        threshold: 12;
        torque: 80;
    };
```

**Comment by PixlOne** [comment]
We should merge the `SmartShift` and `SmartShiftV2` features into a unified `SmartShift` feature. The raw HID++ 2.0 feature interfaces should stay separate though. That way we avoid issues like what @sfllaw described and provide a better abstraction.

Look into how we deal with `RemapButton` and the various versions of `ReprogControls` for more details on implementation.

**Comment by sfllaw** [comment]
Ping? Merging this would help resolve #174 and #262, even if it could be improved further.

**Comment by PixlOne** [comment]
Will look at this again and fix it up for merging, sorry about the delay.

**Review by PixlOne — CHANGES_REQUESTED** [review]
Merge SmartShiftV2 and SmartShift into the same feature

**Review by PixlOne — APPROVED** [review]

**Pull request merged**
